MODULE NCDF

USE NETCDF

IMPLICIT NONE
PRIVATE

INTERFACE GETVAR
  MODULE PROCEDURE GETNCVAR2,GETNCVAR3,GETNCVAR1,GETNCVAI3,GETNCVAR4
END INTERFACE GETVAR

INTERFACE WRITE_VARNCDF
  MODULE PROCEDURE WRITE_VARNCDF_R2D, WRITE_VARNCDF_R3D, WRITE_VARNCDF_I3D, WRITE_VARNCDF_R4D
END INTERFACE WRITE_VARNCDF

PUBLIC :: WRITE_VARNCDF, GETVAR, GETDIM, GETATT

CONTAINS

SUBROUTINE WRITE_VARNCDF_R2D(CFILE,IM,JM,VAR,CVAR,CUNI,CLN)
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER, INTENT(IN) :: IM, JM
REAL, INTENT(IN) :: VAR(IM,JM)
INTEGER :: NCID,DIMIDS1(3),VARID,X_DIMID,Y_DIMID,T_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'time', NF90_UNLIMITED, T_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID, T_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_REAL, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_R2D

SUBROUTINE WRITE_VARNCDF_R3D(CFILE,IM,JM,KM,VAR,CVAR,CUNI,CLN)
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER, INTENT(IN) :: IM, JM, KM
REAL, INTENT(IN) :: VAR(IM,JM,KM)
INTEGER :: NCID,DIMIDS1(4),VARID,X_DIMID,Y_DIMID,Z_DIMID,T_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'z', KM, Z_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'time', NF90_UNLIMITED, T_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID, Z_DIMID, T_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_REAL, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_R3D

SUBROUTINE WRITE_VARNCDF_R4D(CFILE,IM,JM,KM,KT,VAR,CVAR,CUNI,CLN)
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER, INTENT(IN) :: IM, JM, KM, KT
REAL, INTENT(IN) :: VAR(IM,JM,KM,KT)
INTEGER :: NCID,DIMIDS1(4),VARID,X_DIMID,Y_DIMID,Z_DIMID,T_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'z', KM, Z_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'time', NF90_UNLIMITED, T_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID, Z_DIMID, T_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_REAL, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_R4D

SUBROUTINE WRITE_VARNCDF_I3D(CFILE,IM,JM,KM,VAR,CVAR,CUNI,CLN)
CHARACTER(LEN=*), INTENT(IN) :: CFILE,CVAR,CUNI,CLN
INTEGER, INTENT(IN) :: IM, JM, KM
INTEGER, INTENT(IN) :: VAR(IM,JM,KM)
INTEGER :: NCID,DIMIDS1(3),VARID,X_DIMID,Y_DIMID,Z_DIMID
  CALL CHECK( NF90_CREATE(CFILE, NF90_CLOBBER, NCID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'x', IM, X_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'y', JM, Y_DIMID) )
  CALL CHECK( NF90_DEF_DIM(NCID, 'z', KM, Z_DIMID) )
  DIMIDS1=  (/X_DIMID, Y_DIMID, Z_DIMID /)
  CALL CHECK( NF90_DEF_VAR(NCID, CVAR, NF90_INT, DIMIDS1, VARID) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'units',CUNI) )
  CALL CHECK( NF90_PUT_ATT(NCID, VARID, 'long_name',CLN) )
  CALL CHECK( NF90_ENDDEF(NCID) )
  CALL CHECK( NF90_PUT_VAR(NCID, VARID, VAR) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE WRITE_VARNCDF_I3D

SUBROUTINE GETDIM(CF,CD,ND)
  CHARACTER(LEN=*), INTENT(IN) :: CF, CD
  INTEGER, INTENT(OUT) :: ND
  INTEGER :: NCID, DID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_DIMID(NCID,CD,DID) )
  CALL CHECK( NF90_INQUIRE_DIMENSION(NCID,DID,LEN=ND) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETDIM

SUBROUTINE GETATT(CF,CV,CA,ZV)
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV, CA
  REAL   , INTENT(OUT) :: ZV
  INTEGER :: NCID, VID, IRET
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  IRET = NF90_GET_ATT(NCID, VID, CA, ZV)
  IF(IRET .NE. NF90_NOERR) THEN
          IF ( TRIM(CA) .eq. 'add_offset' ) THEN
                  ZV = 0.
          ELSEIF ( TRIM(CA) .eq. 'scale_factor' ) THEN
                  ZV = 1.
          ELSE
                  CALL CHECK(IRET)
          ENDIF
  ENDIF
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETATT

SUBROUTINE GETNCVAR1(CF,CV,JPI,VV)
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER, INTENT(IN) :: JPI
  REAL   , DIMENSION(JPI), INTENT(OUT) :: VV
  INTEGER :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR1

SUBROUTINE GETNCVAR2(CF,CV,JPI,JPJ,VV)
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER, INTENT(IN) :: JPI,JPJ
  REAL   , DIMENSION(JPI,JPJ), INTENT(OUT) :: VV
  INTEGER :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR2

SUBROUTINE GETNCVAR3(CF,CV,JPI,JPJ,JPK,VV)
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER, INTENT(IN) :: JPI,JPJ,JPK
  REAL   , DIMENSION(JPI,JPJ,JPK), INTENT(OUT) :: VV
  INTEGER :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR3

SUBROUTINE GETNCVAR4(CF,CV,JPI,JPJ,JPK,JPT,VV)
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER, INTENT(IN) :: JPI,JPJ,JPK, JPT
  REAL   , DIMENSION(JPI,JPJ,JPK,JPT), INTENT(OUT) :: VV
  INTEGER :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAR4

SUBROUTINE GETNCVAI3(CF,CV,JPI,JPJ,JPK,VV)
  CHARACTER(LEN=*), INTENT(IN) :: CF, CV
  INTEGER, INTENT(IN) :: JPI,JPJ,JPK
  INTEGER, DIMENSION(JPI,JPJ,JPK), INTENT(OUT) :: VV
  INTEGER :: NCID, VID
  CALL CHECK( NF90_OPEN(CF,NF90_NOWRITE,NCID) )
  CALL CHECK( NF90_INQ_VARID(NCID,CV,VID) )
  CALL CHECK( NF90_GET_VAR(NCID,VID,VV) )
  CALL CHECK( NF90_CLOSE(NCID) )
END SUBROUTINE GETNCVAI3

  SUBROUTINE CHECK(STAT)
    INTEGER, INTENT ( IN) :: STAT
    IF(STAT /= NF90_NOERR) THEN
      PRINT *, TRIM(NF90_STRERROR(STAT))
      CALL ABORT
    END IF
  END SUBROUTINE CHECK

END MODULE NCDF
